### ISSUE TITLE
Are these the port-audit schematics?

### ISSUE THREAD

**Issue by ColinGilbert** [Nitrokey/nitrokey-pro-hardware#3]
Hi,

I read the audit at https://cure53.de/pentest-report_nitrokey.pdf and the https://www.nitrokey.com/news/2015/nitrokey-storage-got-great-results-3rd-party-security-audit.

Do these schematics reflect changes made to fix the issues raised?

**Comment by jans23** [comment]
The audit applies to Nitrokey Storage. See https://github.com/Nitrokey/nitrokey-storage-hardware and https://github.com/Nitrokey/nitrokey-storage-firmware
