### ISSUE TITLE
Storage time until loss of data

### ISSUE THREAD

**Issue by MauroMombelli** [Nitrokey/nitrokey-pro-hardware#4]
I'm planning to keep my nitrokey without power for a long amount of time, probably more than a year. Is there any risk to loose the stored keys?
If there is, what is the suggested storage time between recharge?
How long will the battery be reliable?

**Comment by jans23** [comment]
Hi! The Nitrokey doesn't contain a battery and therefore there is no risk of loosing your data/keys when keeping it offline for a few years.

**Comment by MauroMombelli** [comment]
Thanks for the answer, but can you please clarify how data is storage?
AFAIK flash memory will decade? Is this subject to magnetic field? Is safe
to keep the key in a metal box? What if someone pass a strong magnet over
it? What if I keep the sealed box outside (-15 in winter, 40+ in summer)?

**Comment by jans23** [comment]
Usually, magnetic fields and extreme temperatures won't be a problem for you.

Keys are stored in a smart card which is actual EEPROM storage. The specified storage duration is more than 20 years. Regarding magnetic field you find some information [here](https://superuser.com/questions/395876/is-flash-storage-affected-by-magnetic-fields) and [here](https://forums.anandtech.com/threads/should-smartcards-be-affected-by-magnetic-fields.2056204/) for example. A higher temperature **during operation** may decrease its life endurance. For example Microchip has some [good details](http://ww1.microchip.com/downloads/en/AppNotes/01019A.pdf) (although this is not a Microchip product). Extreme temperatures during offline storage shouldn't be a problem.

**Comment by MauroMombelli** [comment]
I think this should be placed somewhere in the description page of the
product, it is quite impressive, and important information for an user.

Thanks for clarification, this exceed my expectation :)
