### ISSUE TITLE
Which design does Nitrokey HSM use?

### ISSUE THREAD

**Issue by persmule** [Nitrokey/nitrokey-pro-hardware#6]
Does Nitrokey HSM use Nitrokey pro's hardware design or something other?

**Comment by szszszsz** [comment]
Hi!
Nitrokey HSM use the same hardware design as Nitrokey Pro. The smart card is different though - it is HSM, not OpenPGP v2.1/v3.3.
On firmware side Nitrokey HSM is not providing as well any Nitrokey App-accessible services (Password Safe, OTP).
